title: Elsa - Global Banhammer
logo: /assets/img/logo.png
description: Use Elsa to allow your users to report other user content.
show_downloads: false
google_analytics: G-VHN9MPH40Q
theme: jekyll-theme-minimal
