title: Elsa - Global Banhammer
logo: /assets/img/logo.png
description: Elsa - Global Banhammer is a telegram bot that allows users to report and ban for the content they post.
show_downloads: false
google_analytics: G-VHN9MPH40Q
theme: jekyll-theme-minimal
